AWSTemplateFormatVersion: "2010-09-09"
Description: Network stack that defines a VPC with one public subnet for EC2 and two private subnets for Multi-AZ RDS.

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16

  PublicSubnetCidr:
    Type: String
    Default: 10.0.1.0/24

  PrivateSubnetACidr:
    Type: String
    Default: 10.0.2.0/24

  PrivateSubnetBCidr:
    Type: String
    Default: 10.0.3.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: sample-vpc

  # ----------------------
  # Internet Gateway
  # ----------------------
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: sample-igw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # ----------------------
  # Public Subnet
  # ----------------------
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetCidr
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: public-subnet-ec2

  # Public Route Table
  #  Public Subnet 用のルートテーブルを作成
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: public-route-table

  PublicRoute:
    Type: AWS::EC2::Route
    # IGWがVPCにアタッチされた後にルートを作るよう設定
    DependsOn: AttachGateway
    Properties:
      # すべての外部通信をIGWへ向ける（インターネット接続）
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # 作成したルートテーブルをPublic Subnet に紐づける
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # ----------------------
  # Private Subnets (RDS)
  # ----------------------
  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetACidr
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: private-subnet-rds-a

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetBCidr
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: private-subnet-rds-b

Outputs:
  VpcId:
    Value: !Ref VPC
    Export:
      Name: Network-VpcId

  PublicSubnetId:
    Value: !Ref PublicSubnet
    Export:
      Name: Network-PublicSubnetId

  PrivateSubnetAId:
    Value: !Ref PrivateSubnetA
    Export:
      Name: Network-PrivateSubnetAId

  PrivateSubnetBId:
    Value: !Ref PrivateSubnetB
    Export:
      Name: Network-PrivateSubnetBId