AWSTemplateFormatVersion: "2010-09-09"
Description: >
  RDS stack
  - Create MySQL RDS with Multi-AZ
  - Allow access only from EC2 Security Group
  - Use Secrets Manager for credentials

######################################
# Parameters
######################################
Parameters:
  VpcId:
    Type: String
    Description: VPC ID (from network-stack)

  PrivateSubnet1A:
    Type: String
    Description: Private Subnet ID in AZ-a

  PrivateSubnet1B:
    Type: String
    Description: Private Subnet ID in AZ-b

  EC2SecurityGroupId:
    Type: String
    Description: EC2 Security Group ID (from security-stack)

  RDSMasterSecretArn:
    Type: String
    Description: ARN of RDS master secret (from secrets-stack)

######################################
# Resources
######################################
Resources:

  ######################################
  # RDS Subnet Group
  # → RDS を配置するサブネット（Multi-AZ用）
  ######################################
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !Ref PrivateSubnet1A
        - !Ref PrivateSubnet1B

  ######################################
  # RDS Security Group
  ######################################
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for RDS
      VpcId: !Ref VpcId

      # インバウンドルール
      # → この EC2 SG が付いているインスタンスからのMySQL(3306) 通信だけを許可する
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref EC2SecurityGroupId

      # アウトバウンドルール
      # → 通常は全許可（RDS から外向き通信はほぼ使わない）
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  ######################################
  # RDS Instance (MySQL)
  ######################################
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: sample-mysql-db
      Engine: mysql
      EngineVersion: "8.0"
      DBInstanceClass: db.t4g.micro

      # Secrets Manager から認証情報を取得(RDS作成時に認証情報必要)
      MasterUsername: !Sub "{{resolve:secretsmanager:${RDSMasterSecretArn}:SecretString:username}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${RDSMasterSecretArn}:SecretString:password}}"

      AllocatedStorage: 20
      StorageType: gp2

      # Multi-AZ 構成（本番想定）
      MultiAZ: true

      # ネットワーク設定
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      PubliclyAccessible: false

      # 削除時の安全設定
      # RDSの自動バックアップを何日保持するか(無料枠なので0設定)
      BackupRetentionPeriod: 0
      # RDS削除保護を有効にするか（false: 削除できる / true: 削除できない）
      DeletionProtection: false

######################################
# Outputs
######################################
Outputs:
  # RDS接続時にエンドポイントが必要なので出力にする
  RDSInstanceEndpoint:
    Description: Endpoint address of RDS
    Value: !GetAtt RDSInstance.Endpoint.Address