AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Secrets Manager stack
  - Store RDS master username and password securely

######################################
# Parameters
######################################
Parameters:
  DBMasterUsername:
    Type: String
    Description: RDS master username
    Default: admin

######################################
# Resources
######################################
Resources:

  ######################################
  # RDS Master Secret
  ######################################
  RDSMasterSecret:
    #Secrets Manager の中に1つの Secretが作られる 
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: rds-master-credentials
      Description: RDS master user credentials

      # username + password を Secrets Manager 側で自動生成
      GenerateSecretString:
        SecretStringTemplate: !Sub |
          {
            "username": "${DBMasterUsername}"
          }
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

######################################
# Outputs
######################################
Outputs:
  ######################################
  # 他スタック（RDS stack）から参照するため
  ######################################
  RDSMasterSecretArn:
    Description: ARN of RDS master secret
    Value: !Ref RDSMasterSecret
    Export:
      Name: RDSMasterSecretArn